<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';

// Get options from the command line.
$shortopts  = "";
$longopts  = array(
  "redmine:",     // Required value
  "apikey:",    // Optional value
);
$options = getopt($shortopts, $longopts);


// Throw error if we got not redmine url.
if (empty($options['redmine'])) {
  throw new ErrorException('No redmine url given');
}
// Throw error if we got not redmine url.
if (empty($options['apikey'])) {
  throw new ErrorException('No apikey given');
}



$client = new Redmine\Client($options['redmine'], $options['apikey']);

$all_users = $client->api('user')->all();
//$client->api('user')->listing();
print_r($all_users);
